name: action-change-audit

on:
  workflow_dispatch:
    inputs:
      start-date:
        required: true
        description: 'Start date for the audit: YYYY-MM-DD'
      end-date:
        required: true
        description: 'End date for the audit: YYYY-MM-DD'

concurrency: this

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  change-audit:
    runs-on: ubuntu-latest
    steps:
      - name: action-change-audit
        uses: champ-oss/action-change-audit@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_DIRECTORY: 'src/prod'
          GITHUB_REPO: 'org/repo'
          WORKING_DIRECTORY: '.'
          REPORT_FILE: '${{ github.event.inputs.start-date }}-report.csv'
          START_DATE: ${{ github.event.inputs.start-date }}
          END_DATE: ${{ github.event.inputs.end-date }}
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: '${{ github.event.inputs.start-date }}-report'
          path: '${{ github.event.inputs.start-date }}-report.csv'
